const LOG_IN = 'LOG_IN';
const LOG_OUT = 'LOG_OUT';
const GET_CONSULTANTS = 'GET_CONSULTANTS';
const GET_USER = 'GET_USER';
const START_LOGGIN = 'START_LOGGIN';
const END_LOGGIN = 'END_LOGGIN';
const ERROR_LOGIN = 'ERROR_LOGIN';

export default {
  LOG_IN,
  LOG_OUT,
  GET_CONSULTANTS,
  GET_USER,
  START_LOGGIN,
  END_LOGGIN,
  ERROR_LOGIN
};
